"""Normal route"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "1",
        "time_difference": 802.0,
        "last_time_in_zone_str": "11:28:22",
        "timetable_id": 893823336,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            28,
            22,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "2",
        "time_difference": 890.0,
        "last_time_in_zone_str": "11:30:50",
        "timetable_id": 893822951,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            30,
            50,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "3",
        "time_difference": 893.0,
        "last_time_in_zone_str": "11:31:53",
        "timetable_id": 893823358,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            31,
            53,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "4",
        "time_difference": 860.0,
        "last_time_in_zone_str": "11:32:20",
        "timetable_id": 893822544,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            32,
            20,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "5",
        "time_difference": 830.0,
        "last_time_in_zone_str": "11:32:50",
        "timetable_id": 893822533,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            32,
            50,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "6",
        "time_difference": 882.0,
        "last_time_in_zone_str": "11:34:42",
        "timetable_id": 893822511,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            34,
            42,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "7",
        "time_difference": 925.0,
        "last_time_in_zone_str": "11:35:25",
        "timetable_id": 893823017,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            35,
            25,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "8",
        "time_difference": 865.0,
        "last_time_in_zone_str": "11:35:25",
        "timetable_id": 893823182,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            35,
            25,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "9",
        "time_difference": 914.0,
        "last_time_in_zone_str": "11:36:14",
        "timetable_id": 893823149,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            36,
            14,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "10",
        "time_difference": 947.0,
        "last_time_in_zone_str": "11:36:47",
        "timetable_id": 893823193,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            36,
            47,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "11",
        "time_difference": 955.0,
        "last_time_in_zone_str": "11:36:55",
        "timetable_id": 893823281,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            36,
            55,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "12",
        "time_difference": 937.0,
        "last_time_in_zone_str": "11:37:37",
        "timetable_id": 893823303,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            37,
            37,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "13",
        "time_difference": 937.0,
        "last_time_in_zone_str": "11:37:37",
        "timetable_id": 893823094,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            37,
            37,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "15",
        "time_difference": 947.0,
        "last_time_in_zone_str": "11:38:47",
        "timetable_id": 893823039,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            38,
            47,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "16",
        "time_difference": 980.0,
        "last_time_in_zone_str": "11:39:20",
        "timetable_id": 893823325,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            39,
            20,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "17",
        "time_difference": 969.0,
        "last_time_in_zone_str": None,
        "timetable_id": 893823050,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            8,
            20,
            11,
            40,
            9,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "18",
        "time_difference": 1003.0,
        "last_time_in_zone_str": None,
        "timetable_id": 893823204,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            8,
            20,
            11,
            40,
            43,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "19",
        "time_difference": 946.0,
        "last_time_in_zone_str": "11:40:46",
        "timetable_id": 893823072,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            40,
            46,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "20",
        "time_difference": 952.0,
        "last_time_in_zone_str": "11:41:52",
        "timetable_id": 893822467,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            41,
            52,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "21",
        "time_difference": 968.0,
        "last_time_in_zone_str": "11:43:08",
        "timetable_id": 893822489,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            43,
            8,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "22",
        "time_difference": 968.0,
        "last_time_in_zone_str": "11:43:08",
        "timetable_id": 893823171,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            43,
            8,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "23",
        "time_difference": 934.0,
        "last_time_in_zone_str": None,
        "timetable_id": 893823138,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            8,
            20,
            11,
            43,
            34,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "24",
        "time_difference": 944.0,
        "last_time_in_zone_str": "11:43:44",
        "timetable_id": 893823127,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            43,
            44,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "25",
        "time_difference": 934.0,
        "last_time_in_zone_str": "11:44:34",
        "timetable_id": 893823116,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            44,
            34,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "26",
        "time_difference": 982.0,
        "last_time_in_zone_str": "11:46:22",
        "timetable_id": 893822588,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            46,
            22,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "27",
        "time_difference": 945.0,
        "last_time_in_zone_str": "11:46:45",
        "timetable_id": 893822599,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            46,
            45,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "28",
        "time_difference": 958.0,
        "last_time_in_zone_str": "11:46:58",
        "timetable_id": 893822610,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            46,
            58,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "29",
        "time_difference": 930.0,
        "last_time_in_zone_str": "11:47:30",
        "timetable_id": 893822874,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            47,
            30,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "30",
        "time_difference": 919.0,
        "last_time_in_zone_str": "11:48:19",
        "timetable_id": 893822852,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            48,
            19,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "31",
        "time_difference": 870.0,
        "last_time_in_zone_str": "11:48:30",
        "timetable_id": 893822819,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            48,
            30,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "32",
        "time_difference": 894.0,
        "last_time_in_zone_str": None,
        "timetable_id": 893822401,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            8,
            20,
            11,
            49,
            54,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "33",
        "time_difference": 868.0,
        "last_time_in_zone_str": "11:50:28",
        "timetable_id": 893822412,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            50,
            28,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "34",
        "time_difference": 935.0,
        "last_time_in_zone_str": "11:51:35",
        "timetable_id": 893822423,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            51,
            35,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "35",
        "time_difference": 968.0,
        "last_time_in_zone_str": "11:53:08",
        "timetable_id": 893822940,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            53,
            8,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "36",
        "time_difference": 1029.0,
        "last_time_in_zone_str": "11:54:09",
        "timetable_id": 893822907,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            54,
            9,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "37",
        "time_difference": 989.0,
        "last_time_in_zone_str": "11:54:29",
        "timetable_id": 893822885,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            54,
            29,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "38",
        "time_difference": 1037.0,
        "last_time_in_zone_str": None,
        "timetable_id": 893822786,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            8,
            20,
            11,
            55,
            17,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "39",
        "time_difference": 1013.0,
        "last_time_in_zone_str": "11:55:53",
        "timetable_id": 893822775,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            55,
            53,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "40",
        "time_difference": 1043.0,
        "last_time_in_zone_str": "11:57:23",
        "timetable_id": 893822753,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            57,
            23,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "41",
        "time_difference": 1083.0,
        "last_time_in_zone_str": "11:58:03",
        "timetable_id": 893822731,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            58,
            3,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "42",
        "time_difference": 1063.0,
        "last_time_in_zone_str": "11:58:43",
        "timetable_id": 893822709,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            58,
            43,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "43",
        "time_difference": 1085.0,
        "last_time_in_zone_str": "11:59:05",
        "timetable_id": 893822698,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            59,
            5,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "45",
        "time_difference": 1077.0,
        "last_time_in_zone_str": "11:59:57",
        "timetable_id": 893822665,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            59,
            57,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "final",
    },
    {
        "group_id": "tlct|378|1215|2024-08-20",
        "stop_index": "44",
        "time_difference": 1047.0,
        "last_time_in_zone_str": "11:59:27",
        "timetable_id": 893822676,
        "last_time_in_zone": datetime.datetime(
            2024,
            8,
            20,
            11,
            59,
            27,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
]


def test_historic_match() -> None:
    run_historic_matching_test(__file__, matches)
