create or replace procedure update_organisation_datasetrevision()
    language plpgsql
as
$$
begin

    --- Update for migration changeset 40 ---
    delete
    from public.organisation_datasetrevision
    where id not in (select distinct id
                     from bods.organisation_datasetrevision);
--- End update for migration changeset 40 ---

    insert into public.organisation_datasetrevision (id,
                                                     created,
                                                     modified,
                                                     upload_file,
                                                     status,
                                                     "name",
                                                     description,
                                                     "comment",
                                                     is_published,
                                                     url_link,
                                                     num_of_lines,
                                                     num_of_operators,
                                                     transxchange_version,
                                                     imported,
                                                     bounding_box,
                                                     publisher_creation_datetime,
                                                     publisher_modified_datetime,
                                                     first_expiring_service,
                                                     last_expiring_service,
                                                     first_service_start,
                                                     num_of_bus_stops,
                                                     dataset_id,
                                                     last_modified_user_id,
                                                     published_by_id,
                                                     published_at,
                                                     "password",
                                                     requestor_ref,
                                                     username,
                                                     short_description,
                                                     num_of_timing_points)
    select id,
           created,
           modified,
           upload_file,
           status,
           "name",
           description,
           "comment",
           is_published,
           url_link,
           num_of_lines,
           num_of_operators,
           transxchange_version,
           imported,
           bounding_box,
           publisher_creation_datetime,
           publisher_modified_datetime,
           first_expiring_service,
           last_expiring_service,
           first_service_start,
           num_of_bus_stops,
           dataset_id,
           last_modified_user_id,
           published_by_id,
           published_at,
           "password",
           requestor_ref,
           username,
           short_description,
           num_of_timing_points
    from bods.organisation_datasetrevision od
    on conflict (id) do update set (
                                    created,
                                    modified,
                                    upload_file,
                                    status,
                                    "name",
                                    description,
                                    "comment",
                                    is_published,
                                    url_link,
                                    num_of_lines,
                                    num_of_operators,
                                    transxchange_version,
                                    imported,
                                    bounding_box,
                                    publisher_creation_datetime,
                                    publisher_modified_datetime,
                                    first_expiring_service,
                                    last_expiring_service,
                                    first_service_start,
                                    num_of_bus_stops,
                                    dataset_id,
                                    last_modified_user_id,
                                    published_by_id,
                                    published_at,
                                    "password",
                                    requestor_ref,
                                    username,
                                    short_description,
                                    num_of_timing_points
                                       )= (
                                           EXCLUDED.created,
                                           EXCLUDED.modified,
                                           EXCLUDED.upload_file,
                                           EXCLUDED.status,
                                           EXCLUDED."name",
                                           EXCLUDED.description,
                                           EXCLUDED."comment",
                                           EXCLUDED.is_published,
                                           EXCLUDED.url_link,
                                           EXCLUDED.num_of_lines,
                                           EXCLUDED.num_of_operators,
                                           EXCLUDED.transxchange_version,
                                           EXCLUDED.imported,
                                           EXCLUDED.bounding_box,
                                           EXCLUDED.publisher_creation_datetime,
                                           EXCLUDED.publisher_modified_datetime,
                                           EXCLUDED.first_expiring_service,
                                           EXCLUDED.last_expiring_service,
                                           EXCLUDED.first_service_start,
                                           EXCLUDED.num_of_bus_stops,
                                           EXCLUDED.dataset_id,
                                           EXCLUDED.last_modified_user_id,
                                           EXCLUDED.published_by_id,
                                           EXCLUDED.published_at,
                                           EXCLUDED."password",
                                           EXCLUDED.requestor_ref,
                                           EXCLUDED.username,
                                           EXCLUDED.short_description,
                                           EXCLUDED.num_of_timing_points
        );
end;
$$;
