[settings]
experimental = true
asdf_compat = true

[tasks.install]
dir = "ingestion_pipelines"
run = "pip install -r requirements.dev.txt"

[tasks.fmt]
run = "ruff format"

[tasks."fmt:check"]
run = "ruff format --check --diff"

[tasks."lint"]
run = "ruff check --fix ."

[tasks."lint:check"]
run = "ruff check ."

[tasks.test]
run = "pytest"

[tasks.checkov]
run = "checkov --baseline .checkov.baseline -d . --skip-path ./venv"

[tasks.fix]
run = [
    "mise tasks run lint || true",
    "mise tasks run fmt",
]

[tasks.checks]
depends = ["checkov", "test", "fmt:check", "lint:check"]

[tasks.example]
run = "assume --exec \"python -m ingestion_pipelines.sirivm_otp_matching_function.sirivm_otp_matching_function.matcher.historic_examples.generate_example\""

[tasks.db]
run = "assume --exec -- ./scripts/db-connect.sh sandbox"

[tasks."db:dev"]
run = "assume --exec -- ./scripts/db-connect.sh dev"

[tasks."db:test"]
run = "assume --exec -- ./scripts/db-connect.sh test"

[tasks."db:uat"]
run = "assume --exec -- ./scripts/db-connect.sh uat"
