"""Bus continues after final stop and creates potential match while moving away from it"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "1",
        "time_difference": 93.0,
        "last_time_in_zone_str": "08:06:33",
        "timetable_id": 1843834296,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            6,
            33,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "2",
        "time_difference": 94.0,
        "last_time_in_zone_str": "08:07:34",
        "timetable_id": 1843834232,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            7,
            34,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "3",
        "time_difference": 76.0,
        "last_time_in_zone_str": "08:10:16",
        "timetable_id": 1843834168,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            10,
            16,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "4",
        "time_difference": 37.0,
        "last_time_in_zone_str": "08:11:37",
        "timetable_id": 1843835969,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            11,
            37,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "5",
        "time_difference": 18.0,
        "last_time_in_zone_str": "08:12:18",
        "timetable_id": 1843836385,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            12,
            18,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "6",
        "time_difference": 78.0,
        "last_time_in_zone_str": "08:13:18",
        "timetable_id": 1843835873,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            13,
            18,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "7",
        "time_difference": 160.0,
        "last_time_in_zone_str": "08:15:40",
        "timetable_id": 1843835713,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            15,
            40,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "8",
        "time_difference": 243.0,
        "last_time_in_zone_str": "08:19:03",
        "timetable_id": 1843834714,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            19,
            3,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "9",
        "time_difference": 283.0,
        "last_time_in_zone_str": "08:19:43",
        "timetable_id": 1843834842,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            19,
            43,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "10",
        "time_difference": 243.0,
        "last_time_in_zone_str": "08:20:03",
        "timetable_id": 1843834874,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            20,
            3,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "11",
        "time_difference": 282.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843834970,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            8,
            20,
            42,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "12",
        "time_difference": 264.0,
        "last_time_in_zone_str": "08:21:24",
        "timetable_id": 1843835002,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            21,
            24,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "13",
        "time_difference": 265.0,
        "last_time_in_zone_str": "08:22:25",
        "timetable_id": 1843836520,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            22,
            25,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "14",
        "time_difference": 245.0,
        "last_time_in_zone_str": "08:23:05",
        "timetable_id": 1843836001,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            23,
            5,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "15",
        "time_difference": 246.0,
        "last_time_in_zone_str": "08:24:06",
        "timetable_id": 1843836289,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            24,
            6,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "16",
        "time_difference": 267.0,
        "last_time_in_zone_str": "08:25:27",
        "timetable_id": 1843836097,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            25,
            27,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "17",
        "time_difference": 246.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835745,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            8,
            26,
            6,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "18",
        "time_difference": 228.0,
        "last_time_in_zone_str": "08:26:48",
        "timetable_id": 1843835841,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            26,
            48,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "19",
        "time_difference": 229.0,
        "last_time_in_zone_str": "08:27:49",
        "timetable_id": 1843836129,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            27,
            49,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "20",
        "time_difference": 269.0,
        "last_time_in_zone_str": "08:28:29",
        "timetable_id": 1843836193,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            28,
            29,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "21",
        "time_difference": 269.0,
        "last_time_in_zone_str": "08:28:29",
        "timetable_id": 1843836225,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            28,
            29,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "22",
        "time_difference": 250.0,
        "last_time_in_zone_str": "08:29:10",
        "timetable_id": 1843835450,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            29,
            10,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "23",
        "time_difference": 150.0,
        "last_time_in_zone_str": "08:29:30",
        "timetable_id": 1843835482,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            29,
            30,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "24",
        "time_difference": 433.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835546,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            8,
            35,
            13,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Late",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "25",
        "time_difference": 395.0,
        "last_time_in_zone_str": "08:35:35",
        "timetable_id": 1843835649,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            35,
            35,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "26",
        "time_difference": 477.0,
        "last_time_in_zone_str": "08:38:57",
        "timetable_id": 1843834264,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            38,
            57,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "27",
        "time_difference": 399.0,
        "last_time_in_zone_str": "08:40:39",
        "timetable_id": 1843834501,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            40,
            39,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "28",
        "time_difference": 319.0,
        "last_time_in_zone_str": "08:41:19",
        "timetable_id": 1843834638,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            41,
            19,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "29",
        "time_difference": 260.0,
        "last_time_in_zone_str": "08:42:20",
        "timetable_id": 1843834513,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            42,
            20,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "30",
        "time_difference": 240.0,
        "last_time_in_zone_str": "08:43:00",
        "timetable_id": 1843834613,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            43,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "31",
        "time_difference": 261.0,
        "last_time_in_zone_str": "08:44:21",
        "timetable_id": 1843834588,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            44,
            21,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "32",
        "time_difference": 242.0,
        "last_time_in_zone_str": "08:45:02",
        "timetable_id": 1843834538,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            45,
            2,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "33",
        "time_difference": 183.0,
        "last_time_in_zone_str": "08:46:03",
        "timetable_id": 1843834576,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            46,
            3,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "34",
        "time_difference": 203.0,
        "last_time_in_zone_str": "08:46:23",
        "timetable_id": 1843836417,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            46,
            23,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "35",
        "time_difference": 143.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835354,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            8,
            47,
            23,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "36",
        "time_difference": 102.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835130,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            8,
            47,
            42,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "37",
        "time_difference": 118.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835162,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            8,
            47,
            58,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "38",
        "time_difference": 64.0,
        "last_time_in_zone_str": "08:48:04",
        "timetable_id": 1843835226,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            48,
            4,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "39",
        "time_difference": 45.0,
        "last_time_in_zone_str": "08:48:45",
        "timetable_id": 1843835258,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            48,
            45,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "40",
        "time_difference": 26.0,
        "last_time_in_zone_str": "08:49:26",
        "timetable_id": 1843835290,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            49,
            26,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "41",
        "time_difference": 1.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835322,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            8,
            50,
            1,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "42",
        "time_difference": -34.0,
        "last_time_in_zone_str": "08:50:26",
        "timetable_id": 1843834746,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            50,
            26,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "43",
        "time_difference": -113.0,
        "last_time_in_zone_str": "08:51:07",
        "timetable_id": 1843834778,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            8,
            51,
            7,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "44",
        "time_difference": 333.0,
        "last_time_in_zone_str": "09:00:33",
        "timetable_id": 1843834360,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            0,
            33,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "45",
        "time_difference": 33.0,
        "last_time_in_zone_str": "09:00:33",
        "timetable_id": 1843834392,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            0,
            33,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "46",
        "time_difference": 10.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843834650,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            9,
            1,
            10,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "47",
        "time_difference": -66.0,
        "last_time_in_zone_str": "09:01:54",
        "timetable_id": 1843835194,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            1,
            54,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "48",
        "time_difference": -95.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835098,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            9,
            2,
            25,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "49",
        "time_difference": -126.0,
        "last_time_in_zone_str": "09:02:54",
        "timetable_id": 1843835066,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            2,
            54,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "50",
        "time_difference": -165.0,
        "last_time_in_zone_str": "09:03:15",
        "timetable_id": 1843834682,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            3,
            15,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "51",
        "time_difference": -185.0,
        "last_time_in_zone_str": "09:03:55",
        "timetable_id": 1843834563,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            3,
            55,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "52",
        "time_difference": 38.0,
        "last_time_in_zone_str": "09:09:38",
        "timetable_id": 1843834550,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            9,
            38,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "53",
        "time_difference": -43.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843834600,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            9,
            10,
            17,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "54",
        "time_difference": -101.0,
        "last_time_in_zone_str": "09:11:19",
        "timetable_id": 1843834525,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            11,
            19,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "55",
        "time_difference": -120.0,
        "last_time_in_zone_str": "09:12:00",
        "timetable_id": 1843834625,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            12,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "56",
        "time_difference": -239.0,
        "last_time_in_zone_str": "09:13:01",
        "timetable_id": 1843834488,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            13,
            1,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "57",
        "time_difference": -298.0,
        "last_time_in_zone_str": "09:15:02",
        "timetable_id": 1843835617,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            15,
            2,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "58",
        "time_difference": -237.0,
        "last_time_in_zone_str": "09:18:03",
        "timetable_id": 1843835386,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            18,
            3,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "59",
        "time_difference": -155.0,
        "last_time_in_zone_str": "09:20:25",
        "timetable_id": 1843835514,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            20,
            25,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "60",
        "time_difference": -217.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843835418,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            9,
            21,
            23,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "61",
        "time_difference": -31.0,
        "last_time_in_zone_str": "09:25:29",
        "timetable_id": 1843834424,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            25,
            29,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "62",
        "time_difference": -91.0,
        "last_time_in_zone_str": "09:25:29",
        "timetable_id": 1843834456,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            25,
            29,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "63",
        "time_difference": -71.0,
        "last_time_in_zone_str": "09:25:49",
        "timetable_id": 1843836161,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            25,
            49,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "64",
        "time_difference": -70.0,
        "last_time_in_zone_str": "09:26:50",
        "timetable_id": 1843835809,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            26,
            50,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "65",
        "time_difference": -70.0,
        "last_time_in_zone_str": "09:27:50",
        "timetable_id": 1843835777,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            27,
            50,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "66",
        "time_difference": -109.0,
        "last_time_in_zone_str": "09:29:11",
        "timetable_id": 1843836257,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            29,
            11,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "67",
        "time_difference": -69.0,
        "last_time_in_zone_str": "09:29:51",
        "timetable_id": 1843836033,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            29,
            51,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "68",
        "time_difference": -148.0,
        "last_time_in_zone_str": "09:30:32",
        "timetable_id": 1843836065,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            30,
            32,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "69",
        "time_difference": -107.0,
        "last_time_in_zone_str": "09:32:13",
        "timetable_id": 1843836488,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            32,
            13,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "70",
        "time_difference": -147.0,
        "last_time_in_zone_str": "09:32:33",
        "timetable_id": 1843835034,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            32,
            33,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "71",
        "time_difference": -114.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1843834938,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            31,
            9,
            33,
            6,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "72",
        "time_difference": -207.0,
        "last_time_in_zone_str": "09:33:33",
        "timetable_id": 1843834906,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            33,
            33,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "73",
        "time_difference": -44.0,
        "last_time_in_zone_str": "09:36:16",
        "timetable_id": 1843834810,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            36,
            16,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "74",
        "time_difference": -3.0,
        "last_time_in_zone_str": "09:37:57",
        "timetable_id": 1843836353,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            37,
            57,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "75",
        "time_difference": -2.0,
        "last_time_in_zone_str": "09:39:58",
        "timetable_id": 1843835681,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            39,
            58,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "76",
        "time_difference": 38.0,
        "last_time_in_zone_str": "09:40:38",
        "timetable_id": 1843835905,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            40,
            38,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "77",
        "time_difference": -1.0,
        "last_time_in_zone_str": "09:40:59",
        "timetable_id": 1843836321,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            40,
            59,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "78",
        "time_difference": -100.0,
        "last_time_in_zone_str": "09:42:20",
        "timetable_id": 1843835937,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            42,
            20,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "79",
        "time_difference": -139.0,
        "last_time_in_zone_str": "09:43:41",
        "timetable_id": 1843834200,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            43,
            41,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-31",
    },
    {
        "group_id": "scem|9|11|2024-10-31",
        "stop_index": "80",
        "time_difference": -358.0,
        "last_time_in_zone_str": "09:46:02",
        "timetable_id": 1843834329,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            31,
            9,
            46,
            2,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
        "date_of_journey": "2024-10-31",
    },
]


def test_historic_match() -> None:
    assert run_historic_matching_test(__file__) == matches
