"""Journey that runs over midnight"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "18",
        "time_difference": 243.0,
        "last_time_in_zone_str": "22:49:03",
        "timetable_id": 1746993908,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            22,
            49,
            3,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "19",
        "time_difference": 316.0,
        "last_time_in_zone_str": "22:51:16",
        "timetable_id": 1746993972,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            22,
            51,
            16,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "20",
        "time_difference": 290.0,
        "last_time_in_zone_str": "22:51:50",
        "timetable_id": 1746994004,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            22,
            51,
            50,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "21",
        "time_difference": 354.0,
        "last_time_in_zone_str": "22:54:54",
        "timetable_id": 1746994068,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            22,
            54,
            54,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "22",
        "time_difference": 361.0,
        "last_time_in_zone_str": "22:56:01",
        "timetable_id": 1746994484,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            22,
            56,
            1,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "23",
        "time_difference": 334.0,
        "last_time_in_zone_str": "22:56:34",
        "timetable_id": 1746994516,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            22,
            56,
            34,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "24",
        "time_difference": 350.0,
        "last_time_in_zone_str": "22:59:50",
        "timetable_id": 1746994548,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            22,
            59,
            50,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "25",
        "time_difference": 376.0,
        "last_time_in_zone_str": "23:00:16",
        "timetable_id": 1746994580,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            23,
            0,
            16,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "26",
        "time_difference": 338.0,
        "last_time_in_zone_str": "23:00:38",
        "timetable_id": 1746994612,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            23,
            0,
            38,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "27",
        "time_difference": 355.0,
        "last_time_in_zone_str": "23:00:55",
        "timetable_id": 1746994644,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            23,
            0,
            55,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "28",
        "time_difference": 318.0,
        "last_time_in_zone_str": "23:01:18",
        "timetable_id": 1746994676,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            23,
            1,
            18,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "29",
        "time_difference": 325.0,
        "last_time_in_zone_str": "23:02:25",
        "timetable_id": 1746994100,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            23,
            2,
            25,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "30",
        "time_difference": 367.0,
        "last_time_in_zone_str": "23:04:07",
        "timetable_id": 1746994132,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            23,
            4,
            7,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "group_id": "amid|158|1069|2024-10-25",
        "stop_index": "31",
        "time_difference": 347.0,
        "last_time_in_zone_str": "23:04:47",
        "timetable_id": 1746994164,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            25,
            23,
            4,
            47,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
    },
]


def test_historic_match() -> None:
    assert run_historic_matching_test(__file__) == matches
