"""Journey that starts after midnight from a late running service"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "stop_index": "1",
        "time_difference": 180.0,
        "last_time_in_zone_str": "00:04:00",
        "timetable_id": 2792841889,
        "last_time_in_zone": datetime.datetime(2025, 2, 19, 0, 4, tzinfo=datetime.UTC),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "2",
        "time_difference": 244.0,
        "last_time_in_zone_str": "00:06:04",
        "timetable_id": 2792839998,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            6,
            4,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "4",
        "time_difference": 305.0,
        "last_time_in_zone_str": "00:07:05",
        "timetable_id": 2792841953,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            7,
            5,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "6",
        "time_difference": 306.0,
        "last_time_in_zone_str": "00:08:06",
        "timetable_id": 2792841877,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            8,
            6,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "8",
        "time_difference": 307.0,
        "last_time_in_zone_str": "00:09:07",
        "timetable_id": 2792840018,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            9,
            7,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "10",
        "time_difference": 286.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792842234,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            19,
            0,
            10,
            46,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "11",
        "time_difference": 248.0,
        "last_time_in_zone_str": "00:11:08",
        "timetable_id": 2792842214,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            11,
            8,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "14",
        "time_difference": 130.0,
        "last_time_in_zone_str": "00:13:10",
        "timetable_id": 2792841770,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            13,
            10,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "16",
        "time_difference": 132.0,
        "last_time_in_zone_str": "00:14:12",
        "timetable_id": 2792845197,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            14,
            12,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "20",
        "time_difference": 77.0,
        "last_time_in_zone_str": "00:21:17",
        "timetable_id": 2792841480,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            21,
            17,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "24",
        "time_difference": 444.0,
        "last_time_in_zone_str": "00:31:24",
        "timetable_id": 2792841308,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            31,
            24,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "25",
        "time_difference": 385.0,
        "last_time_in_zone_str": "00:32:25",
        "timetable_id": 2792841259,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            32,
            25,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "28",
        "time_difference": 354.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792840108,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            19,
            0,
            34,
            54,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "29",
        "time_difference": 328.0,
        "last_time_in_zone_str": "00:36:28",
        "timetable_id": 2792841088,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            36,
            28,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "32",
        "time_difference": 347.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792841957,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            19,
            0,
            38,
            47,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "33",
        "time_difference": 271.0,
        "last_time_in_zone_str": "00:39:31",
        "timetable_id": 2792840941,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            39,
            31,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "36",
        "time_difference": 215.0,
        "last_time_in_zone_str": "00:41:35",
        "timetable_id": 2792840758,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            41,
            35,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "39",
        "time_difference": 157.0,
        "last_time_in_zone_str": "00:43:37",
        "timetable_id": 2792840660,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            43,
            37,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "44",
        "time_difference": -20.0,
        "last_time_in_zone_str": "00:45:40",
        "timetable_id": 2792840415,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            45,
            40,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "51",
        "time_difference": -72.0,
        "last_time_in_zone_str": "00:49:48",
        "timetable_id": 2792845246,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            49,
            48,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
    },
]


def test_historic_match() -> None:
    assert run_historic_matching_test(__file__) == matches
