"""Journey that runs over midnight"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "stop_index": "1",
        "time_difference": 2.0,
        "last_time_in_zone_str": "22:30:02",
        "timetable_id": 2792964420,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            22,
            30,
            2,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "2",
        "time_difference": 117.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792964460,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            18,
            22,
            33,
            57,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "3",
        "time_difference": -55.0,
        "last_time_in_zone_str": "22:41:05",
        "timetable_id": 2792964540,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            22,
            41,
            5,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "4",
        "time_difference": -102.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792964920,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            18,
            22,
            42,
            18,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "5",
        "time_difference": -134.0,
        "last_time_in_zone_str": "22:42:46",
        "timetable_id": 2792964900,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            22,
            42,
            46,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "6",
        "time_difference": -114.0,
        "last_time_in_zone_str": "22:43:06",
        "timetable_id": 2792964860,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            22,
            43,
            6,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "7",
        "time_difference": -143.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792964980,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            18,
            22,
            44,
            37,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "8",
        "time_difference": -172.0,
        "last_time_in_zone_str": "22:47:08",
        "timetable_id": 2792965040,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            22,
            47,
            8,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "9",
        "time_difference": 216.0,
        "last_time_in_zone_str": "23:08:36",
        "timetable_id": 2792965941,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            23,
            8,
            36,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "12",
        "time_difference": 360.0,
        "last_time_in_zone_str": "23:18:00",
        "timetable_id": 2792964721,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            23,
            18,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Late",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "13",
        "time_difference": 296.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792964681,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            18,
            23,
            19,
            56,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "20",
        "time_difference": 266.0,
        "last_time_in_zone_str": "23:27:26",
        "timetable_id": 2792964581,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            18,
            23,
            27,
            26,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "23",
        "time_difference": 303.0,
        "last_time_in_zone_str": None,
        "timetable_id": 2792965681,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2025,
            2,
            18,
            23,
            31,
            3,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "31",
        "time_difference": 26.0,
        "last_time_in_zone_str": "00:36:26",
        "timetable_id": 2792965242,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            36,
            26,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "32",
        "time_difference": 213.0,
        "last_time_in_zone_str": "00:55:33",
        "timetable_id": 2792965302,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            0,
            55,
            33,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "33",
        "time_difference": -80.0,
        "last_time_in_zone_str": "01:14:40",
        "timetable_id": 2792965323,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            1,
            14,
            40,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "34",
        "time_difference": -51.0,
        "last_time_in_zone_str": "01:30:09",
        "timetable_id": 2792965183,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            1,
            30,
            9,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "36",
        "time_difference": -63.0,
        "last_time_in_zone_str": "01:47:57",
        "timetable_id": 2792965443,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            1,
            47,
            57,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "37",
        "time_difference": -122.0,
        "last_time_in_zone_str": "01:51:58",
        "timetable_id": 2792965423,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            1,
            51,
            58,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "stop_index": "38",
        "time_difference": -80.0,
        "last_time_in_zone_str": "01:56:40",
        "timetable_id": 2792965383,
        "last_time_in_zone": datetime.datetime(
            2025,
            2,
            19,
            1,
            56,
            40,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
    },
]


def test_historic_match() -> None:
    assert run_historic_matching_test(__file__) == matches
