CREATE TABLE public.transmodel_servicepatterndistance (
id int8 GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 NO MAXVALUE START 0 NO CYCLE) NOT NULL,
distance int4 NULL,
geom public.geometry(linestring, 4326) NULL,
service_pattern_id int4 NULL,
CONSTRAINT fk_service_pattern FOREIGN KEY (service_pattern_id)
REFERENCES public.transmodel_servicepattern(id)
ON DELETE CASCADE
);


ALTER TABLE expected_services_by_date
ADD COLUMN IF NOT EXISTS total_distance INTEGER,
ADD COLUMN IF NOT EXISTS avl_true_distance INTEGER;
