CREATE TABLE public.transmodel_servicepatterndistance (
id int8 GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 NO MAXVALUE START 0 NO CYCLE) NOT NULL,
distance int4 NULL,
geom public.geometry(linestring, 4326) NULL,
service_pattern_id int4 NULL,
CONSTRAINT fk_service_pattern FOREIGN KEY (service_pattern_id)
REFERENCES public.transmodel_servicepattern(id)
ON DELETE CASCADE
);


ALTER TABLE expected_services_by_date
ADD COLUMN IF NOT EXISTS total_distance INTEGER,
ADD COLUMN IF NOT EXISTS avl_true_distance INTEGER;

DROP MATERIALIZED VIEW IF EXISTS public.expected_services;

CREATE MATERIALIZED VIEW public.expected_services
TABLESPACE pg_default
AS
SELECT DISTINCT 
    esbd.date_of_journey,
    sd.noc_and_line_and_servicecode,
    sd.operator_noc,
    sd.line_name,
    sd.service_name,
    esbd.admin_area_id,
    esbd.total_distance,
    esbd.avl_true_distance
FROM 
    expected_services_by_date esbd
LEFT JOIN 
    service_details sd 
    ON esbd.noc_and_line_and_servicecode = sd.noc_and_line_and_servicecode
WITH DATA;
