"""Group id with split inbound/outbound timetable"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "1",
        "time_difference": 41.0,
        "last_time_in_zone_str": "07:40:41",
        "timetable_id": 2426929616,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            40,
            41,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "1",
        "time_difference": 46.0,
        "last_time_in_zone_str": "07:40:46",
        "timetable_id": 2426930563,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            40,
            46,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "2",
        "time_difference": 61.0,
        "last_time_in_zone_str": "07:43:01",
        "timetable_id": 2426929476,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            43,
            1,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "3",
        "time_difference": 166.0,
        "last_time_in_zone_str": "07:46:46",
        "timetable_id": 2426929432,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            46,
            46,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "2",
        "time_difference": 88.0,
        "last_time_in_zone_str": "07:48:28",
        "timetable_id": 2426930468,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            48,
            28,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "3",
        "time_difference": 52.0,
        "last_time_in_zone_str": "07:49:52",
        "timetable_id": 2426930420,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            49,
            52,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "4",
        "time_difference": 24.0,
        "last_time_in_zone_str": "07:52:24",
        "timetable_id": 2426930278,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            52,
            24,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "4",
        "time_difference": 176.0,
        "last_time_in_zone_str": "07:52:56",
        "timetable_id": 2426929388,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            52,
            56,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "5",
        "time_difference": 74.0,
        "last_time_in_zone_str": "07:54:14",
        "timetable_id": 2426930183,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            54,
            14,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "5",
        "time_difference": 144.0,
        "last_time_in_zone_str": "07:54:24",
        "timetable_id": 2426929898,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            54,
            24,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "6",
        "time_difference": 37.0,
        "last_time_in_zone_str": "07:56:37",
        "timetable_id": 2426929806,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            56,
            37,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "6",
        "time_difference": 156.0,
        "last_time_in_zone_str": "07:56:36",
        "timetable_id": 2426929993,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            56,
            36,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "7",
        "time_difference": 184.0,
        "last_time_in_zone_str": "07:58:04",
        "timetable_id": 2426930088,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            7,
            58,
            4,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "7",
        "time_difference": 22.0,
        "last_time_in_zone_str": "08:00:22",
        "timetable_id": 2426929759,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            0,
            22,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "8",
        "time_difference": 145.0,
        "last_time_in_zone_str": "08:00:25",
        "timetable_id": 2426929711,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            0,
            25,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "8",
        "time_difference": 18.0,
        "last_time_in_zone_str": "08:03:18",
        "timetable_id": 2426930136,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            3,
            18,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "9",
        "time_difference": 156.0,
        "last_time_in_zone_str": "08:03:36",
        "timetable_id": 2426929855,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            3,
            36,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "9",
        "time_difference": 29.0,
        "last_time_in_zone_str": "08:05:29",
        "timetable_id": 2426930041,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            5,
            29,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "10",
        "time_difference": 148.0,
        "last_time_in_zone_str": "08:06:28",
        "timetable_id": 2426930232,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            6,
            28,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "10",
        "time_difference": 38.0,
        "last_time_in_zone_str": "08:07:38",
        "timetable_id": 2426929946,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            7,
            38,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "11",
        "time_difference": 148.0,
        "last_time_in_zone_str": "08:08:28",
        "timetable_id": 2426930327,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            8,
            28,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "12",
        "time_difference": 176.0,
        "last_time_in_zone_str": "08:09:56",
        "timetable_id": 2426930374,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            9,
            56,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "11",
        "time_difference": 61.0,
        "last_time_in_zone_str": "08:10:01",
        "timetable_id": 2426929344,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            10,
            1,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "13",
        "time_difference": 144.0,
        "last_time_in_zone_str": "08:11:24",
        "timetable_id": 2426930517,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            11,
            24,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "14",
        "time_difference": 13.0,
        "last_time_in_zone_str": "08:19:13",
        "timetable_id": 2426930612,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            19,
            13,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "12",
        "time_difference": -21.0,
        "last_time_in_zone_str": "08:19:39",
        "timetable_id": 2426929524,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            19,
            39,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "13",
        "time_difference": -51.0,
        "last_time_in_zone_str": "08:22:09",
        "timetable_id": 2426929572,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            22,
            9,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "fbri|m4|0740|2025-01-10",
        "stop_index": "14",
        "time_difference": -43.0,
        "last_time_in_zone_str": "08:25:17",
        "timetable_id": 2426929664,
        "last_time_in_zone": datetime.datetime(
            2025,
            1,
            10,
            8,
            25,
            17,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
    },
]


def test_historic_match() -> None:
    run_historic_matching_test(__file__, matches)
