"""Bus going to starting point to start the journey and matching backwards"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "1",
        "time_difference": 47.0,
        "last_time_in_zone_str": "15:30:47",
        "timetable_id": 1790856819,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            30,
            47,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "2",
        "time_difference": 113.0,
        "last_time_in_zone_str": "15:33:37",
        "timetable_id": 1790857071,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            33,
            37,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "3",
        "time_difference": 142.0,
        "last_time_in_zone_str": "15:35:22",
        "timetable_id": 1790856877,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            35,
            22,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "4",
        "time_difference": 129.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856871,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            35,
            47,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "5",
        "time_difference": 111.0,
        "last_time_in_zone_str": "15:35:57",
        "timetable_id": 1790856858,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            35,
            57,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "6",
        "time_difference": 111.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856900,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            36,
            51,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "7",
        "time_difference": 130.0,
        "last_time_in_zone_str": "15:37:23",
        "timetable_id": 1790856832,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            37,
            23,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "8",
        "time_difference": 137.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856845,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            37,
            43,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "10",
        "time_difference": 137.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790857034,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            38,
            39,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "11",
        "time_difference": 171.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790857021,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            41,
            51,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "12",
        "time_difference": 128.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790857001,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            43,
            46,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "13",
        "time_difference": 101.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856988,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            44,
            45,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "14",
        "time_difference": 102.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856982,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            45,
            9,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "15",
        "time_difference": 114.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856969,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            45,
            54,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "16",
        "time_difference": 119.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856956,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            46,
            29,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "17",
        "time_difference": 41.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856936,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            15,
            47,
            30,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "18",
        "time_difference": -17.0,
        "last_time_in_zone_str": "15:48:43",
        "timetable_id": 1790856925,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            48,
            43,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "19",
        "time_difference": 22.0,
        "last_time_in_zone_str": "15:49:43",
        "timetable_id": 1790856906,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            49,
            43,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "24",
        "time_difference": -65.0,
        "last_time_in_zone_str": "15:59:01",
        "timetable_id": 1790856786,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            15,
            59,
            1,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "Early",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "25",
        "time_difference": -41.0,
        "last_time_in_zone_str": "16:00:39",
        "timetable_id": 1790856728,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            16,
            0,
            39,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "26",
        "time_difference": 22.0,
        "last_time_in_zone_str": "16:02:22",
        "timetable_id": 1790856720,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            16,
            2,
            22,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "27",
        "time_difference": 26.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856712,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            16,
            2,
            44,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "28",
        "time_difference": 16.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1790856704,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            10,
            17,
            16,
            3,
            33,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "29",
        "time_difference": 1.0,
        "last_time_in_zone_str": "16:04:06",
        "timetable_id": 1790856692,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            16,
            4,
            6,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
        "date_of_journey": "2024-10-17",
    },
    {
        "group_id": "coac|41|1630|2024-10-17",
        "stop_index": "34",
        "time_difference": -99.0,
        "last_time_in_zone_str": "16:07:21",
        "timetable_id": 1790856771,
        "last_time_in_zone": datetime.datetime(
            2024,
            10,
            17,
            16,
            7,
            21,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
        "date_of_journey": "2024-10-17",
    },
]


def test_historic_match() -> None:
    assert run_historic_matching_test(__file__) == matches
