"""Bus starting early"""

import datetime

from ..util import run_historic_matching_test

matches = [
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "1",
        "time_difference": 202.0,
        "last_time_in_zone_str": "12:08:22",
        "timetable_id": 1891077807,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            8,
            22,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "2",
        "time_difference": 203.0,
        "last_time_in_zone_str": "12:09:23",
        "timetable_id": 1891077743,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            9,
            23,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "3",
        "time_difference": 104.0,
        "last_time_in_zone_str": "12:10:44",
        "timetable_id": 1891077679,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            10,
            44,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "4",
        "time_difference": 127.0,
        "last_time_in_zone_str": "12:13:07",
        "timetable_id": 1891079480,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            13,
            7,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "5",
        "time_difference": 105.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891079896,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            12,
            13,
            45,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "6",
        "time_difference": 168.0,
        "last_time_in_zone_str": "12:14:48",
        "timetable_id": 1891079384,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            14,
            48,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "7",
        "time_difference": 148.0,
        "last_time_in_zone_str": "12:15:28",
        "timetable_id": 1891079224,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            15,
            28,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "8",
        "time_difference": 130.0,
        "last_time_in_zone_str": "12:17:10",
        "timetable_id": 1891078225,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            17,
            10,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "9",
        "time_difference": 145.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891078353,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            12,
            17,
            25,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "10",
        "time_difference": 170.0,
        "last_time_in_zone_str": "12:17:50",
        "timetable_id": 1891078385,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            17,
            50,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "11",
        "time_difference": 151.0,
        "last_time_in_zone_str": "12:18:31",
        "timetable_id": 1891078481,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            18,
            31,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "12",
        "time_difference": 192.0,
        "last_time_in_zone_str": "12:19:12",
        "timetable_id": 1891078513,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            19,
            12,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "13",
        "time_difference": 172.0,
        "last_time_in_zone_str": "12:19:52",
        "timetable_id": 1891080031,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            19,
            52,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "14",
        "time_difference": 213.0,
        "last_time_in_zone_str": "12:20:33",
        "timetable_id": 1891079512,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            20,
            33,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "15",
        "time_difference": 214.0,
        "last_time_in_zone_str": "12:21:34",
        "timetable_id": 1891079800,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            21,
            34,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "16",
        "time_difference": 194.0,
        "last_time_in_zone_str": "12:22:14",
        "timetable_id": 1891079608,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            22,
            14,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "17",
        "time_difference": 195.0,
        "last_time_in_zone_str": "12:23:15",
        "timetable_id": 1891079256,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            23,
            15,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "18",
        "time_difference": 236.0,
        "last_time_in_zone_str": "12:23:56",
        "timetable_id": 1891079352,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            23,
            56,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "19",
        "time_difference": 257.0,
        "last_time_in_zone_str": "12:25:17",
        "timetable_id": 1891079640,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            25,
            17,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "20",
        "time_difference": 275.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891079704,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            12,
            25,
            35,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "21",
        "time_difference": 275.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891079736,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            12,
            25,
            35,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "52",
        "time_difference": -1824.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891077935,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            12,
            25,
            36,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "53",
        "time_difference": -1824.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891077967,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            12,
            25,
            36,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "Early",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "53",
        "time_difference": 21.0,
        "last_time_in_zone_str": "12:56:21",
        "timetable_id": 1891077967,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            56,
            21,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "54",
        "time_difference": 40.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891079672,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            12,
            56,
            40,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "55",
        "time_difference": 42.0,
        "last_time_in_zone_str": "12:57:42",
        "timetable_id": 1891079320,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            57,
            42,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "56",
        "time_difference": 23.0,
        "last_time_in_zone_str": "12:58:23",
        "timetable_id": 1891079288,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            12,
            58,
            23,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "57",
        "time_difference": 125.0,
        "last_time_in_zone_str": "13:00:05",
        "timetable_id": 1891079768,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            0,
            5,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "58",
        "time_difference": 206.0,
        "last_time_in_zone_str": "13:02:26",
        "timetable_id": 1891079544,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            2,
            26,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "59",
        "time_difference": 246.0,
        "last_time_in_zone_str": "13:03:06",
        "timetable_id": 1891079576,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            3,
            6,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "60",
        "time_difference": 247.0,
        "last_time_in_zone_str": "13:04:07",
        "timetable_id": 1891079999,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            4,
            7,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "61",
        "time_difference": 208.0,
        "last_time_in_zone_str": "13:04:28",
        "timetable_id": 1891078545,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            4,
            28,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "62",
        "time_difference": 248.0,
        "last_time_in_zone_str": "13:05:08",
        "timetable_id": 1891078449,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            5,
            8,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "63",
        "time_difference": 229.0,
        "last_time_in_zone_str": "13:05:49",
        "timetable_id": 1891078417,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            5,
            49,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "64",
        "time_difference": 261.0,
        "last_time_in_zone_str": None,
        "timetable_id": 1891078321,
        "last_time_in_zone": None,
        "timestamp_after_estimate": datetime.datetime(
            2024,
            11,
            6,
            13,
            6,
            21,
            tzinfo=datetime.UTC,
        ),
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "65",
        "time_difference": 271.0,
        "last_time_in_zone_str": "13:07:31",
        "timetable_id": 1891079864,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            7,
            31,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "69",
        "time_difference": 73.0,
        "last_time_in_zone_str": "13:10:13",
        "timetable_id": 1891079448,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            10,
            13,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "70",
        "time_difference": 35.0,
        "last_time_in_zone_str": "13:12:35",
        "timetable_id": 1891077711,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            12,
            35,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "Non-final",
    },
    {
        "group_id": "scem|9|27|2024-11-06",
        "stop_index": "71",
        "time_difference": -203.0,
        "last_time_in_zone_str": "13:14:37",
        "timetable_id": 1891077840,
        "last_time_in_zone": datetime.datetime(
            2024,
            11,
            6,
            13,
            14,
            37,
            tzinfo=datetime.UTC,
        ),
        "timestamp_after_estimate": None,
        "otp_state": "OnTime",
        "stop_type": "final",
    },
]


def test_historic_match() -> None:
    run_historic_matching_test(__file__, matches)
