name: Merge deployment pull request

on:
  pull_request_review:
    types: [submitted]

permissions:
  id-token: write

jobs:
  merge-deployment-pr:
    if: github.event.review.state == 'approved' && contains(fromJSON('["refs/heads/dev", "refs/heads/test", "refs/heads/main"]'), github.event.pull_request.base.ref)
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: merge
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
        git fetch
        git checkout $(${{ github.event.pull_request.base.ref }} | sed 's:.*/::')
        git reset $(${{ github.event.pull_request.head.ref }} | sed 's:.*/::')
        git push
