name: modify database
run-name:
  modify database from ${{ github.ref_name }} @ ${{ (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) && 'prod' ||
  github.ref_name == 'test' && 'test' ||
  github.ref_name == 'cavl' && 'cavl' ||
  github.ref_name == 'uat' && 'uat' ||
  github.ref_name == 'dev' && 'dev' || 'sandbox' }}
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        default: "run-migrations"
        description: database modification action
        options:
          - "refresh"
          - "destroy"
          - "initialise"
          - "run-migrations"

concurrency:
  group:
    ${{ github.workflow }}-${{ (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) && 'prod' ||
    github.ref_name == 'test' && 'test' ||
    github.ref_name == 'cavl' && 'cavl' ||
    github.ref_name == 'uat' && 'uat' ||
    github.ref_name == 'dev' && 'dev' || 'sandbox' }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  DEPLOY_ACT: ${{ github.event.inputs.action }}
  DEPLOY_ENV:
    ${{ (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) && 'prod' ||
    github.ref_name == 'test' && 'test' ||
    github.ref_name == 'cavl' && 'cavl' ||
    github.ref_name == 'uat' && 'uat' ||
    github.ref_name == 'dev' && 'dev' || 'sandbox' }}
  DEPLOY_SRC: ${{ vars.DEPLOYMENT_ARTEFACTS_S3_BUCKET }}
  DEPLOY_VER: ${{ github.ref_name != 'main' && github.ref_name || 'null' }}

jobs:
  validation:
    runs-on: ubuntu-latest
    environment:
      ${{ (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) && 'prod' ||
      github.ref_name == 'test' && 'test' ||
      github.ref_name == 'cavl' && 'cavl' ||
      github.ref_name == 'uat' && 'uat' ||
      github.ref_name == 'dev' && 'dev' || 'sandbox' }}
    outputs:
      AWS_ACCOUNT_ID: ${{ steps.set-vars.outputs.AWS_ACCOUNT_ID }}
      REMOTE_DB_HOST_ID: ${{ steps.set-vars.outputs.REMOTE_DB_HOST_ID }}
      REMOTE_DB_HOSTNAME: ${{ steps.set-vars.outputs.REMOTE_DB_HOSTNAME }}
      VERSION: ${{ steps.verify.outputs.VERSION }}

    steps:
      - name: validate job parameters
        id: verify
        run: |
          get_latest_version() {
            local bucket_name=$1
            local prefix_path=$2

            directories=$(aws s3 ls s3://$bucket_name/$prefix_path/ --summarize --human-readable | grep -E 'PRE|DIR' | awk '{print $2}')
            latest_version=""
            while IFS= read -r dir; do
              version=$(basename "$dir")
              if [[ $version =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
                if [[ -z $latest_version ]] || (( $(echo "$version" | awk -F '.' '{print $1*10000+$2*100+$3}') > $(echo "$latest_version" | awk -F '.' '{print $1*10000+$2*100+$3}') )); then
                  latest_version=$version
                fi
              fi
            done <<< "$directories"
            echo "$latest_version"
          }

          if [[ $DEPLOY_ACT == 'run-migrations' || $DEPLOY_ACT == 'refresh' ]]; then
            if [[ ${DEPLOY_VER} != 'null' ]]; then
              echo """ \
                Modifying backend database using parameters:
                  (Database Action)        - $DEPLOY_ACT
                  (Release Version)        - ${DEPLOY_VER//\//-}
                  (Deployment Environment) - $DEPLOY_ENV
              """
              echo "VERSION=${DEPLOY_VER//\//-}" >> "$GITHUB_OUTPUT"
            else
              echo [INFO] Deploying from main branch. Using latest tagged version
              latest_version=$(get_latest_version $DEPLOY_SRC 'abods-itm/releases')
              echo """ \
                Modifying backend database using parameters:
                  (Database Action)        - $DEPLOY_ACT
                  (Release Version)        - $latest_version (latest)
                  (Deployment Environment) - $DEPLOY_ENV
              """
              echo "VERSION=${latest_version}" >> "$GITHUB_OUTPUT"
            fi
          else
              echo """ \
              Modifying backend database using parameters:
                (Database Action)        - $DEPLOY_ACT
                (Deployment Environment) - $DEPLOY_ENV
            """
          fi

      - name: set environment specific vars
        id: set-vars
        run: |
          echo "AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT
          echo "REMOTE_DB_HOST_ID=${{ vars.REMOTE_DB_HOST_ID }}" >> $GITHUB_OUTPUT
          echo "REMOTE_DB_HOSTNAME=${{ vars.REMOTE_DB_HOSTNAME }}" >> $GITHUB_OUTPUT

  database:
    runs-on: ubuntu-latest
    needs: validation

    permissions:
      id-token: write
      contents: read

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ needs.validation.outputs.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ env.DEPLOY_ENV }}-database-modification
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: run database destroy against ${{ env.DEPLOY_ENV }}
        if: ${{ env.DEPLOY_ACT == 'destroy' || env.DEPLOY_ACT == 'refresh' }}
        run: |
          lambda_function_name="${{ vars.PROJECT_NAME }}-${DEPLOY_ENV}-pglifecycle-function"
          cat <<EOF > $GITHUB_WORKSPACE/payload.json
          {
            "type": "destroy",
            "authUser": "root",
            "targetDatabase": "${{ vars.PROJECT_NAME }}",
            "roles": [
              "${{ vars.PROJECT_NAME }}_ro",
              "${{ vars.PROJECT_NAME }}_iam_ro",
              "${{ vars.PROJECT_NAME }}_proxy_ro",
              "${{ vars.PROJECT_NAME }}_rw",
              "${{ vars.PROJECT_NAME }}_iam_rw",
              "${{ vars.PROJECT_NAME }}_proxy_rw"
            ]
          }
          EOF

          openssl base64 -out $GITHUB_WORKSPACE/encoded_payload.json -in $GITHUB_WORKSPACE/payload.json 
          response=$(aws lambda invoke --function-name $lambda_function_name --region $AWS_REGION --payload file://$GITHUB_WORKSPACE/encoded_payload.json response.txt 2>&1)
          status_code=$(cat response.txt | jq -r '.statusCode')
          status_code=${status_code:-"unset"}
          echo "Status Code is: $status_code"
          if [[ "$status_code" == "500" ]]; then
            echo "[ERROR] Destruction of database failed against ${DEPLOY_ENV^^} with error:"
            echo "${response}"
            exit 1
          else
            response_payload=$(cat response.txt)
            echo "Response Payload: $response_payload"
            echo "[INFO] Destruction of database successfully run against ${DEPLOY_ENV^^}"
          fi

      - name: run database initialisation against ${{ env.DEPLOY_ENV }}
        if: ${{ env.DEPLOY_ACT == 'initialise' || env.DEPLOY_ACT == 'refresh' }}
        run: |
          lambda_function_name="${{ vars.PROJECT_NAME }}-${DEPLOY_ENV}-pglifecycle-function"
          cat <<EOF > $GITHUB_WORKSPACE/payload.json
          {
              "type": "initialise",
              "authUser": "root",
              "databases": [{
                  "name": "${{ vars.PROJECT_NAME }}",
                  "schemas": [
                      "bods",
                      "partman",
                      "public"
                  ],
                  "extensions": [
                      "aws_commons",
                      "aws_s3+cascade",
                      "pg_cron",
                      "pg_partman:partman",
                      "postgis",
                      "postgres_fdw"
                  ],
                  "servers": [{
                      "name": "bods",
                      "options": {
                          "host": "${{ needs.validation.outputs.REMOTE_DB_HOSTNAME }}",
                          "port": 5432,
                          "dbname": "bodds"
                      },
                      "userMappings": [{
                          "name": "root",
                          "credentialsArn": "${{ vars.PROJECT_NAME }}/${DEPLOY_ENV}/rds/server/${{ needs.validation.outputs.REMOTE_DB_HOST_ID }}"
                      },{
                          "name": "${{ vars.PROJECT_NAME }}_rw",
                          "credentialsArn": "${{ vars.PROJECT_NAME }}/${DEPLOY_ENV}/rds/server/${{ needs.validation.outputs.REMOTE_DB_HOST_ID }}"
                      },{
                          "name": "${{ vars.PROJECT_NAME }}_iam_rw",
                          "credentialsArn": "${{ vars.PROJECT_NAME }}/${DEPLOY_ENV}/rds/server/${{ needs.validation.outputs.REMOTE_DB_HOST_ID }}"
                      },{
                          "name": "${{ vars.PROJECT_NAME }}_proxy_rw",
                          "credentialsArn": "${{ vars.PROJECT_NAME }}/${DEPLOY_ENV}/rds/server/${{ needs.validation.outputs.REMOTE_DB_HOST_ID }}"
                      }]
                  }]
              }],
              "datadogMonitoring": {
                "enabled": true,
                "authType": "scram",
                "credentialsArn": "${{ vars.PROJECT_NAME }}/${DEPLOY_ENV}/rds/user/datadog"
              },
              "roles": [{
                  "name": "${{ vars.PROJECT_NAME }}_ro",
                  "kind": "ro",
                  "users": [{
                      "name": "${{ vars.PROJECT_NAME }}_iam_ro",
                      "authType": "iam"
                  },{
                      "name": "${{ vars.PROJECT_NAME }}_proxy_ro",
                      "authType": "scram",
                      "credentialsArn": "${{ vars.PROJECT_NAME }}/${DEPLOY_ENV}/rds/user/${{ vars.PROJECT_NAME }}_proxy_ro"
                  }]
              },{
                  "name": "${{ vars.PROJECT_NAME }}_rw",
                  "kind": "rw",
                  "schemas": ["cron", "aws_s3"],
                  "users": [{
                      "name": "${{ vars.PROJECT_NAME }}_iam_rw",
                      "authType": "iam"
                  },{
                      "name": "${{ vars.PROJECT_NAME }}_proxy_rw",
                      "authType": "scram",
                      "credentialsArn": "${{ vars.PROJECT_NAME }}/${DEPLOY_ENV}/rds/user/${{ vars.PROJECT_NAME }}_proxy_rw"
                  }]
              }]
          }
          EOF

          openssl base64 -out $GITHUB_WORKSPACE/encoded_payload.json -in $GITHUB_WORKSPACE/payload.json 
          response=$(aws lambda invoke --function-name $lambda_function_name --region $AWS_REGION --payload file://$GITHUB_WORKSPACE/encoded_payload.json response.txt 2>&1)
          status_code=$(cat response.txt | jq -r '.statusCode')
          status_code=${status_code:-"unset"}
          echo "Status Code is: $status_code"
          if [[ "$status_code" == "500" ]]; then
            echo "[ERROR] Initialisation of database failed against ${DEPLOY_ENV^^} with error:"
            echo "${response}"
            exit 1
          else
            response_payload=$(cat response.txt)
            echo "Response Payload: $response_payload"
            echo "[INFO] Initialisation of database successfully run against ${DEPLOY_ENV^^}"
          fi

      - name: run database migrations against ${{ env.DEPLOY_ENV }}
        if: ${{ env.DEPLOY_ACT == 'run-migrations' || env.DEPLOY_ACT == 'refresh' }}
        env:
          VERSION: ${{ needs.validation.outputs.VERSION }}
        run: |
          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="abods-itm/releases" || rc_path="abods-itm/releases"
          lambda_function_name="${{ vars.PROJECT_NAME }}-${DEPLOY_ENV}-pglifecycle-function"
          cat <<EOF > $GITHUB_WORKSPACE/payload.json
          {
            "type": "run_migrations",
            "authUser": "${{ vars.PROJECT_NAME }}_proxy_rw",
            "targetDatabase": "${{ vars.PROJECT_NAME }}",
            "databaseMigrations": {
              "bucketName": "${DEPLOY_SRC}",
              "bucketPrefix": "$rc_path",
              "releaseVersion": "${VERSION}"
            }
          }
          EOF

          openssl base64 -out $GITHUB_WORKSPACE/encoded_payload.json -in $GITHUB_WORKSPACE/payload.json 
          response=$(aws lambda invoke --function-name $lambda_function_name --region $AWS_REGION --payload file://$GITHUB_WORKSPACE/encoded_payload.json response.txt 2>&1)
          status_code=$(cat response.txt | jq -r '.statusCode')
          status_code=${status_code:-"unset"}
          echo "Status Code is: $status_code"
          if [[ "$status_code" == "500" ]]; then
            echo "[ERROR] Execution of database migrations failed for version ${VERSION} against ${DEPLOY_ENV^^} with error:"
            echo "${response}"
            exit 1
          else
            response_payload=$(cat response.txt)
            echo "Response Payload: $response_payload"
            echo "[INFO] Execution of database migrations successfully run against ${DEPLOY_ENV^^} for version ${VERSION}"
          fi
