name: Ruff
on: [pull_request]
permissions: read-all
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        name: "lint"
        with:
          version: "0.13.0"
          args: "check"
      - uses: astral-sh/ruff-action@v1
        name: "format"
        with:
          version: "0.13.0"
          args: "format --check"
